# Generated by Django 4.1.7 on 2023-05-01 14:53

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('offer_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('Entreprise', models.CharField(max_length=150)),
                ('Titre', models.CharField(max_length=150)),
                ('Date', models.DateField()),
                ('Description', django_mysql.models.SizedTextField(size_class=3)),
                ('Lieu', models.CharField(max_length=150)),
                ('Salaire', models.CharField(max_length=45)),
                ('url', models.CharField(max_length=150)),
            ],
        ),
    ]
