# Generated by Django 4.1.7 on 2023-05-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joboffers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='offer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
