# Generated by Django 4.1.7 on 2023-05-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joboffers', '0002_alter_joboffer_offer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='img',
            field=models.CharField(default='test', max_length=150),
            preserve_default=False,
        ),
    ]
