# Generated by Django 4.1.7 on 2023-05-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joboffers', '0004_joboffer_experience_joboffer_diplome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='Experience',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='diplome',
            field=models.CharField(max_length=100),
        ),
    ]
