# Generated by Django 4.1.7 on 2023-05-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joboffers', '0005_alter_joboffer_experience_alter_joboffer_diplome'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='SalaireMax',
            field=models.CharField(default='ns', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joboffer',
            name='SalaireMin',
            field=models.CharField(default='ns', max_length=10),
            preserve_default=False,
        ),
    ]
